name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [published]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pull all history with tags for correct versionning
      run: git fetch --prune --unshallow

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Cache SBT ivy cache
      uses: actions/cache@v1
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}
        restore-keys: |
          ${{ runner.os }}-sbt-ivy-cache-

    - name: Cache SBT
      uses: actions/cache@v1
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
        restore-keys: |
          ${{ runner.os }}-sbt-

    - name: Checks
      run: |
        git config --global user.name "CI"
        ./mill all __.checkFormat "__.fix --check" __.docJar __.test


    - name: Publish
      if: github.ref == 'refs/heads/master' || github.event_name == 'release'
      run: |
        echo "${{ secrets.PGP_SECRET }}" > private.key
        gpg --batch --yes --import private.key
        rm private.key

        ./mill mill.scalalib.PublishModule/publishAll --sonatypeCreds ${{ secrets.SONATYPE_USERNAME }}:${{ secrets.SONATYPE_PASSWORD }} --gpgArgs --passphrase,${{ secrets.PGP_PASSPHRASE }},--batch,--yes,-a,-b --publishArtifacts __.publishArtifacts --awaitTimeout 600000 --release true
