name: Publish

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      PGP_PASSWORD: ${{ secrets.PGP_PASSPHRASE }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Run tests
      run: ./sbt "+ test"
    
    - name: Publish
      uses: DamianReeves/sbt-maven-publish@master
      with:
        sonatype-username: ${{ secrets.SONATYPE_USERNAME }}
        sonatype-password: ${{ secrets.SONATYPE_PASSWORD }}
        pgp-secret: ${{ secrets.PGP_SECRET }}
        pgp-passphrase: ${{ secrets.PGP_PASSPHRASE }}
        pgp-passphrase-variable-name: "PGP_PASSWORD"
        pgp-public-key: ${{ secrets.PGP_PUBLIC_KEY }}
        
